plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
	mavenCentral()
}

dependencies {

	// Spring Data
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// Spring Web
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Mysql
	runtimeOnly 'com.mysql:mysql-connector-j'

	// mapstruct
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	// jwt
	implementation 'io.jsonwebtoken:jjwt:0.12.5'
	
	// spring security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	
	// spring mail
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	
	// bucket4j
	implementation 'com.bucket4j:bucket4j-core:8.7.0'	

	// json
	implementation 'com.googlecode.json-simple:json-simple:1.1.1'

	// apache commons
	implementation 'org.apache.commons:commons-text:1.10.0'

	// redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// Spring AI
	implementation platform("org.springframework.ai:spring-ai-bom:1.0.0-SNAPSHOT")
    implementation 'org.springframework.ai:spring-ai-openai'
    implementation 'org.springframework.ai:spring-ai-openai-spring-boot-starter'
	
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
