spring:
  application:
    name: lettuce
    client-base-url: ${CLIENT_BASE_URL}

  config:
    import:
      - optional:file:.env[.properties]
      - optional:classpath:application-mysql.yml
      - optional:classpath:application-redis.yml
      - optional:classpath:application-cloud.yml

  servlet:
    multipart:
      max-file-size: 10MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  jwt:
    secret: ${JWT_SECRET}
    access-token-expire-time: 6h
    refresh-token-expire-time: 1d

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

  crawler:
    coupang:
      base-url: ${COUPANG_BASE_URL}
      base-product-url: ${COUPANG_PRODUCT_URL}
      list-url: ${COUPANG_LIST_URL}
